spring:
  application:
    name: shop-app-backend
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop-app
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  logging:
    level:
      org:
        springframework:
          security: DEBUG
api:
  prefix: /api/v1
app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 259200000
  base-url: http://localhost:8080/
redis:
  host: localhost
  port: 6380
